### ISSUE TITLE
Download bert models

### ISSUE THREAD

**Issue by DbrRoxane** [Microsoft/SDNet#2]
Hi,

I have download bert-large-uncased from  "https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased.tar.gz", which only gives me the pytorch_model.bin and bert_config.json. 
In order to get the bert-large-uncased-vocab.txt missing, I've downloaded the model from https://github.com/google-research/bert and renamed vocab.txt into bert-large-uncased-vocab.txt

I guess that it was not the right solution because I got an error

```
Using BERT Large model
Loading tokenizer from ../coqa/bert-large-uncased/bert-large-uncased-vocab.txt
02/27/2019 14:02:02 - INFO - Models.Bert.tokenization -   loading vocabulary file ../coqa/bert-large-uncased/bert-large-uncased-vocab.txt
*****************
prev_ques   : 2
prev_ans    : 2
ques_max_len: 140
****************
/path/SDNet/Models/SDNet.py:286: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha_softmax = F.softmax(alpha)
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model.train()
  File "/path/SDNet/Models/SDNetTrainer.py", line 126, in train
    self.update(batch)
  File "/path/SDNet/Models/SDNetTrainer.py", line 182, in update
    targets = torch.LongTensor(np.array(targets))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.
```

Any idea about the place I can get the data or fix it??

**Comment by zcgzcgzcg1** [comment]
That's interesting. Because that's how I get the vocab. Can you share more details about target?

**Comment by zcgzcgzcg1** [comment]
I have uploaded the vocab files I used for BERT at: https://github.com/Microsoft/SDNet/tree/master/bert_vocab_files

**Comment by Arjunsankarlal** [comment]
Hi @zcgzcgzcg1 can you please upload the vocab files for other bert models as well (bert-large-cased, bert-base-uncased)

**Comment by DbrRoxane** [comment]
I am very sorry because I could not answer before but I still have the same issue with your file. The  stack is exactly the same as before. 

I don't know of ot can help but here is the complete stack
```
Using Cuda

SDNet Model Trainer
CoQA Preprocessing
Select command: train
Saving logs, model and evaluation in ../coqa/conf~/run_7
Load train_meta.msgpack...
-----------------------------------------------
Initializing model...
SDNet model

Using BERT
Loading BERT model...
Using BERT Large model
Loading BERT model from ../coqa/bert-large-uncased/
03/19/2019 09:30:15 - INFO - Models.Bert.modeling -   loading archive file ../coqa/bert-large-uncased/
03/19/2019 09:30:15 - INFO - Models.Bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "max_position_embeddings": 512,
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

Finished loading
Lock BERT's weights
BERT_LARGE
BERT dim: 1024 BERT_LAYERS: 24
BERT_LINEAR_COMBINE
path/SDNet/Models/SDNet.py:82: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  torch.nn.init.constant(self.alphaBERT, 1.0)
path/SDNet/Models/SDNet.py:83: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  torch.nn.init.constant(self.gammaBERT, 1.0)
Initially, the vector_sizes [doc, query] are 1648 1324
After Input LSTM, the vector_sizes [doc, query] are [ 250 250 ] * 2
Self deep-attention input is 1800-dim
Do Question self attention
Before answer span finding, hidden size are 250 250
Putting model into GPU
Loading train json...
Loading dev json...
Epoch 0
Using BERT Large model
Loading tokenizer from ../coqa/bert-large-uncased/bert-large-uncased-vocab.txt
03/19/2019 09:31:21 - INFO - Models.Bert.tokenization -   loading vocabulary file ../coqa/bert-large-uncased/bert-large-uncased-vocab.txt
*****************
prev_ques   : 2
prev_ans    : 2
ques_max_len: 140
*****************
Using BERT Large model
Loading tokenizer from ../coqa/bert-large-uncased/bert-large-uncased-vocab.txt
03/19/2019 09:31:21 - INFO - Models.Bert.tokenization -   loading vocabulary file ../coqa/bert-large-uncased/bert-large-uncased-vocab.txt
*****************
prev_ques   : 2
prev_ans    : 2
ques_max_len: 140
*****************
path/SDNet/Models/SDNet.py:286: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha_softmax = F.softmax(alpha)
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model.train()
  File "/path/SDNet/Models/SDNetTrainer.py", line 126, in train
    self.update(batch)
  File "path/SDNet/Models/SDNetTrainer.py", line 182, in update
    targets = torch.LongTensor(np.array(targets))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.

```

**Comment by DbrRoxane** [comment]
OK solved
It was because of pyTorch version
1.0 generates this issue
0.4.0 generates an other issue during training
0.4.1 works

It would be helpul to indicate ti use 0.4.1 in the README or event write a requirement.txt 

Have a nice day,
