### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by Arjunsankarlal** [Microsoft/SDNet#7]
While training I am getting this error

> Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model.train()
  File "/home/SDNet/Models/SDNetTrainer.py", line 126, in train
    self.update(batch)
  File "/home/SDNet/Models/SDNetTrainer.py", line 164, in update
    query, query_mask, query_char, query_char_mask, query_bert, query_bert_mask, query_bert_offsets, len(context_words))
  File "/home/SDNet/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/SDNet/Models/SDNet.py", line 253, in forward
    x_highlvl_output = self.high_lvl_context_rnn(torch.cat([x_rnn_after_inter_attn, x_self_attn_output], 2), x_mask)
  File "/home/raisudeen/SDNet/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/SDNet/Models/Layers.py", line 163, in forward
    rnn_output = self.rnns[i](rnn_input)[0]
  File "/home/SDNet/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/crm-di/raisudeen/SDNet/env/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 192, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "/home/SDNet/env/lib/python3.7/site-packages/torch/nn/_functions/rnn.py", line 324, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/SDNet/env/lib/python3.7/site-packages/torch/nn/_functions/rnn.py", line 288, in forward
    dropout_ts)
RuntimeError: CUDA error: out of memory

I have tried changing the mini batch size from 32 to all the way to 2 (tried 16,8,4 as well). I am using GTX 1080 Ti GPU. Is there anything else that I can do to?

**Comment by zcgzcgzcg1** [comment]
We used V100 GPU to train and it has 16GB memory. So you can try using multi-gpu. Another way is to use BERT-base. Finally, accumulating gradients can help: https://discuss.pytorch.org/t/how-to-implement-accumulated-gradient/3822
